title: inf-2201 Operating system fundamentals (Spring 2021)

description: > # this means to ignore newlines until "contact:"
  Course description.

contact:
  email: lars.ailo.bongo@uit.no
  name: Lars Ailo Bongo

# you don't need to adapt the settings below
baseurl: ""
markdown: kramdown
